# Generated by Django 5.0.3 on 2024-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_localiza_pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristica',
            options={'verbose_name': 'Caracteristica'},
        ),
        migrations.AddField(
            model_name='bichinho_post',
            name='caract',
            field=models.ManyToManyField(to='app_localiza_pet.caracteristica'),
        ),
    ]
