# Generated by Django 5.0.3 on 2024-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_localiza_pet', '0002_alter_caracteristica_options_bichinho_post_caract'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('arq', models.ImageField(upload_to='img')),
            ],
        ),
    ]
