# Generated by Django 5.0.3 on 2024-05-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_localiza_pet', '0003_myfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bichinho_post',
            name='caract',
        ),
        migrations.RemoveField(
            model_name='bichinho_post',
            name='user',
        ),
        migrations.CreateModel(
            name='Animal_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='img')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Caracteristica',
        ),
        migrations.DeleteModel(
            name='Bichinho_post',
        ),
    ]
