# Generated by Django 5.0.3 on 2024-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_localiza_pet', '0004_remove_bichinho_post_caract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_post',
            name='title',
        ),
        migrations.AddField(
            model_name='animal_post',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
