# Generated by Django 5.0.3 on 2024-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_localiza_pet', '0005_remove_animal_post_title_animal_post_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_post',
            name='opcao',
            field=models.CharField(choices=[('1', 'Adoção'), ('0', 'Perdido')], default='0', max_length=20),
        ),
    ]
