# Generated by Django 5.0.3 on 2024-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_localiza_pet', '0006_animal_post_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_post',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
